### ISSUE TITLE
Beta build 1.0.1 fails compilation

### ISSUE THREAD

**Issue by dvershinin** [reverbdotcom/reverb-magento-2#1]
/usr/bin/php -f /var/www/html/bin/magento setup:di:compile

Results in:

```
Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% < 1 sec 52.0 MiBPHP Warning:  Uncaught Exception: Warning: require_once(Reverb/ProcessQueue/controllers/Adminhtml/ProcessQueue/IndexController.php): failed to open stream: No such file or directory in /var/www/html/app/code/Reverb/ProcessQueue/Controller/Adminhtml/Processqueue/Unique/IndexController.php on line 2 in /var/www/html/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 /var/www/html/app/code/Reverb/ProcessQueue/Controller/Adminhtml/Processqueue/Unique/IndexController.php(2): Magento\Framework\App\ErrorHandler->handler(2, 'require_once(Re...', '/srv/www/lvguit...', 2, Array)
#1 /var/www/html/app/code/Reverb/ProcessQueue/Controller/Adminhtml/Processqueue/Unique/IndexController.php(2): require_once()
#2 /var/www/html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(123): require_once('/srv/www/lvguit...')
#3 /var/www/html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(108): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->inclu in /var/www/html/vendor/magento/framework/App/ErrorHandler.php on line 61
PHP Fatal error:  Magento\Setup\Module\Di\Code\Reader\ClassesScanner::main(): Failed opening required 'Reverb/ProcessQueue/controllers/Adminhtml/ProcessQueue/IndexController.php' (include_path='/var/www/html/generated/code:/var/www/html/generated/code:/var/www/html/vendor/magento/zendframework1/library:.:/usr/share/pear:/usr/share/php') in /var/www/html/app/code/Reverb/ProcessQueue/Controller/Adminhtml/Processqueue/Unique/IndexController.php on line 2
```

**Comment by kevinecd** [comment]
Most recent release (1.0.2) removed legacy code preventing compilation.

Leaving this issue open until we've confirmed fixed.

**Comment by dvershinin** [comment]
Doesn't seem like anything has changed:

```
Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% < 1 sec 62.0 MiBPHP Warning:  Uncaught Exception: Warning: require_once(Reverb/ProcessQueue/controllers/Adminhtml/ProcessQueue/IndexController.php): failed to open stream: No such file or directory in /srv/www/staging.lvguitars.com/app/code/Reverb/ProcessQueue/Controller/Adminhtml/Processqueue/Unique/IndexController.php on line 2 in /srv/www/staging.lvguitars.com/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 /srv/www/staging.lvguitars.com/app/code/Reverb/ProcessQueue/Controller/Adminhtml/Processqueue/Unique/IndexController.php(2): Magento\Framework\App\ErrorHandler->handler(2, 'require_once(Re...', '/srv/www/stagin...', 2, Array)
#1 /srv/www/staging.lvguitars.com/app/code/Reverb/ProcessQueue/Controller/Adminhtml/Processqueue/Unique/IndexController.php(2): require_once()
#2 /srv/www/staging.lvguitars.com/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(123): require_once('/srv/www/stagin...')
#3 /srv/www/staging.lvguitars.com/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(108): Magento\S in /srv/www/staging.lvguitars.com/vendor/magento/framework/App/ErrorHandler.php on line 61
PHP Fatal error:  Magento\Setup\Module\Di\Code\Reader\ClassesScanner::main(): Failed opening required 'Reverb/ProcessQueue/controllers/Adminhtml/ProcessQueue/IndexController.php' (include_path='/srv/www/staging.lvguitars.com/generated/code:/srv/www/staging.lvguitars.com/generated/code:/srv/www/staging.lvguitars.com/vendor/magento/zendframework1/library:.:/usr/share/pear:/usr/share/php') in /srv/www/staging.lvguitars.com/app/code/Reverb/ProcessQueue/Controller/Adminhtml/Processqueue/Unique/IndexController.php on line 2
```

**Comment by kevinecd** [comment]
Mistake on the last commit.  Ran the wrong command before doing last commit and did not delete files from the repo.  Release 1.0.3 is reflects removal of files.

**Comment by dvershinin** [comment]
I confirm it compiles fine now with 1.0.3.
