### ISSUE TITLE
Sync cron shamelessly fails with 1.0.6

### ISSUE THREAD

**Issue by dvershinin** [reverbdotcom/reverb-magento-2#5]
The ```reverb_process_queued_listing_sync_tasks``` fails with fatal PHP error:

```
Run \Reverb\ReverbSync\Model\Cron\Listings\Sync::attemptCronExecution PHP Fatal error:  Uncaught Error: Class 'Reverb\ReverbSync\Helper\Exception' not found in /var/www/html/app/code/Reverb/ReverbSync/Helper/Data.php:266
Stack trace:
#0 /var/www/html/app/code/Reverb/ReverbSync/Helper/Data.php(83): Reverb\ReverbSync\Helper\Data->findReverbListingUrlByMagentoSku('LMH1000NTQMSTP')
#1 /var/www/html/app/code/Reverb/ReverbSync/Helper/Sync/Product.php(161): Reverb\ReverbSync\Helper\Data->createOrUpdateReverbListing(Object(Magento\Catalog\Model\Product\Interceptor), false)
#2 /var/www/html/app/code/Reverb/ReverbSync/Helper/Sync/Product.php(126): Reverb\ReverbSync\Helper\Sync\Product->executeSimpleProductSync(Object(Magento\Catalog\Model\Product\Interceptor), false)
#3 /var/www/html/app/code/Reverb/ReverbSync/Model/Sync/Product.php(62): Reverb\ReverbSync\Helper\Sync\Product->executeIndividualProductDataSync(5819)
#4 /var/www/html/app/code/Reverb/ProcessQueue/Model/Task.php(89): Reverb\ReverbSync\Model\Sync\Product->executeQueuedIndividualProductDataSy in /var/www/html/app/code/Reverb/ReverbSync/Helper/Data.php on line 266
```

**Comment by dunagan5887** [comment]
@dvershinin Given that I implemented the Magento 1.x version of this extension (I unfortunately had nothing to do with the 2.x version) I can resolve any issues that you're running in to. Please let me know if you'd like to discuss putting together some work to address all of the many issues with the 2.x version of this extension
