### ISSUE TITLE
Fieldset issues

### ISSUE THREAD

**Issue by Lach1222** [reverbdotcom/reverb-magento-2#9]
Hi we are receiving the following error after install the reverb module.

1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): The XML in file "/home/cmcadm1n/public_html/magento2/app/code/Reverb/ReverbSync/etc/fieldset.xml" is invalid:
Element 'fieldsets': This element is not expected. Expected is ( fieldset ).
Line: 4

Verify the XML and try again.

Exception #0 (Magento\Framework\Exception\LocalizedException): The XML in file "/home/cmcadm1n/public_html/magento2/app/code/Reverb/ReverbSync/etc/fieldset.xml" is invalid:
Element 'fieldsets': This element is not expected. Expected is ( fieldset ).
Line: 4

Verify the XML and try again.
#0 /home/cmcadm1n/public_html/magento2/vendor/magento/framework/Config/Reader/Filesystem.php(132): Magento\Framework\Config\Reader\Filesystem->_readFiles(Object(Magento\Framework\Config\FileIterator))
#1 /home/cmcadm1n/public_html/magento2/generated/code/Magento/Framework/DataObject/Copy/Config/Reader/Proxy.php(95): Magento\Framework\Config\Reader\Filesystem->read('global')
#2 /home/cmcadm1n/public_html/magento2/vendor/magento/framework/Config/Data.php(105): Magento\Framework\DataObject\Copy\Config\Reader\Proxy->read()
#3 /home/cmcadm1n/public_html/magento2/vendor/magento/framework/Config/Data.php(93): Magento\Framework\Config\Data->initData()
#4 /home/cmcadm1n/public_html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(116): Magento\Framework\Config\Data->__construct(Object(Magento\Framework\DataObject\Copy\Config\Reader\Proxy), Object(Magento\Framework\App\Cache\Type\Config), 'fieldset_config', NULL)
#5 /home/cmcadm1n/public_html/magento2/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#6 /home/cmcadm1n/public_html/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Framewo...')
#7 /home/cmcadm1n/public_html/magento2/vendor/magento/framework/DataObject/Copy/Config/Data/Proxy.php(96): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#8 /home/cmcadm1n/public_html/magento2/vendor/magento/framework/DataObject/Copy/Config/Data/Proxy.php(115): Magento\Framework\DataObject\Copy\Config\Data\Proxy->_getSubject()
#9 /home/cmcadm1n/public_html/magento2/vendor/magento/framework/DataObject/Copy/Config.php(31): Magento\Framework\DataObject\Copy\Config\Data\Proxy->get('global')
#10 /home/cmcadm1n/public_html/magento2/vendor/magento/framework/DataObject/Copy/Config.php(43): Magento\Framework\DataObject\Copy\Config->getFieldsets('global')
#11 /home/cmcadm1n/public_html/magento2/vendor/magento/framework/DataObject/Copy.php(67): Magento\Framework\DataObject\Copy\Config->getFieldset('customer_accoun...', 'global')
#12 /home/cmcadm1n/public_html/magento2/vendor/magento/module-quote/Model/Quote.php(989): Magento\Framework\DataObject\Copy->copyFieldsetToTarget('customer_accoun...', 'to_quote', Object(Magento\Framework\DataObject), Object(Magento\Quote\Model\Quote\Interceptor))
#13 /home/cmcadm1n/public_html/magento2/generated/code/Magento/Quote/Model/Quote/Interceptor.php(518): Magento\Quote\Model\Quote->setCustomer(Object(Magento\Customer\Model\Data\Customer))
#14 /home/cmcadm1n/public_html/magento2/vendor/magento/module-checkout/Model/Session.php(259): Magento\Quote\Model\Quote\Interceptor->setCustomer(Object(Magento\Customer\Model\Data\Customer))
#15 /home/cmcadm1n/public_html/magento2/generated/code/Magento/Checkout/Model/Session/Interceptor.php(63): Magento\Checkout\Model\Session->getQuote()
#16 /home/cmcadm1n/public_html/magento2/vendor/magento/module-persistent/Observer/EmulateQuoteObserver.php(100): Magento\Checkout\Model\Session\Interceptor->getQuote()
#17 /home/cmcadm1n/public_html/magento2/vendor/magento/framework/Event/Invoker/InvokerDefault.php(72): Magento\Persistent\Observer\EmulateQuoteObserver->execute(Object(Magento\Framework\Event\Observer))
#18 /home/cmcadm1n/public_html/magento2/vendor/magento/framework/Event/Invoker/InvokerDefault.php(60): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\Persistent\Observer\EmulateQuoteObserver), Object(Magento\Framework\Event\Observer))
#19 /home/cmcadm1n/public_html/magento2/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#20 /home/cmcadm1n/public_html/magento2/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('controller_acti...', Array)
#21 /home/cmcadm1n/public_html/magento2/vendor/magento/framework/App/Action/Action.php(97): Magento\Framework\Event\Manager\Proxy->dispatch('controller_acti...', Array)
#22 /home/cmcadm1n/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#23 /home/cmcadm1n/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Cms\Controller\Index\Index\Interceptor->___callParent('dispatch', Array)
#24 /home/cmcadm1n/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Cms\Controller\Index\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#25 /home/cmcadm1n/public_html/magento2/generated/code/Magento/Cms/Controller/Index/Index/Interceptor.php(39): Magento\Cms\Controller\Index\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#26 /home/cmcadm1n/public_html/magento2/vendor/magento/framework/App/FrontController.php(159): Magento\Cms\Controller\Index\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#27 /home/cmcadm1n/public_html/magento2/vendor/magento/framework/App/FrontController.php(99): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Magento\Cms\Controller\Index\Index\Interceptor))
#28 /home/cmcadm1n/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#29 /home/cmcadm1n/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#30 /home/cmcadm1n/public_html/magento2/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#31 /home/cmcadm1n/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#32 /home/cmcadm1n/public_html/magento2/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#33 /home/cmcadm1n/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#34 /home/cmcadm1n/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#35 /home/cmcadm1n/public_html/magento2/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#36 /home/cmcadm1n/public_html/magento2/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#37 /home/cmcadm1n/public_html/magento2/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#38 /home/cmcadm1n/public_html/magento2/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http\Interceptor->launch()
#39 /home/cmcadm1n/public_html/magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#40 {main}

**Comment by Lach1222** [comment]
#10 Fixed with this Pull Request, as a result of Magento 2.3 changing support and method for fieldset.
